query Fetch_Plays {
  plays {
    blog
    component
    cover
    created_at
    description
    featured
    github
    owner_user_id
    id
    language
    level {
      id
      name
    }
    name
    path
    play_tags {
      tag {
        id
        name
      }
    }
    updated_at
    user {
      id
      displayName
      avatarUrl
      userProviders {
        accessToken
      }
    }
    video
  }
}