query Fetch_Plays {
  plays {
    blog
    component
    cover
    created_at
    description
    featured
    github
    id
    language
    level {
      id
      name
    }
    level_id
    name
    owner_user_id
    path
    play_tags {
      tag {
        id
        name
        created_at
        updated_at
      }
    }
    updated_at
    user {
      id
    }
    video
  }
}